version: '3'

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    volumes:
     - ./frontend/:/usr/share/nginx/html
    ports:
     - 80:80
    networks:
     - app-network
  server:
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
