version: '3'

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
    networks:
     - app-network
    depends_on:
     - server
     
  server:
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

